# Simple Linear Regression

# Import relevant libraries

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

# Load the data

In [18]:
data = pd.read_csv("1.02. Multiple linear regression.csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

# Create the regression

# Declare the dependent and independent variables

In [19]:
x = data[["SAT", "Rand 1,2,3"]]
y = data["GPA"]

In [20]:
x.shape

(84, 2)

In [21]:
y.shape

(84,)

In [22]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(168, 1)

# Regression itself

In [23]:
reg = LinearRegression()

In [24]:
reg.fit(x, y)

LinearRegression()

# R-squared

In [25]:
reg.score(x,y)

0.4066811952814282

# Coefficients

In [26]:
reg.coef_

array([ 0.00165354, -0.00826982])

# Intercept

In [27]:
reg.intercept_

0.29603261264909353

# Making predictions

In [28]:
#data=1740
#data = data.values.reshape(-1,1)
#reg.predict(1740)

In [29]:
new_data =pd.DataFrame(data=[1740, 1760], columns=["SAT"])
new_data

SAT
0  1740
1  1760

In [30]:
reg.predict(new_data)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [31]:
new_data["Predicted GPA"] = reg.predict(new_data)
new_data

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [ ]:
plt.scatter(x,y)
yhat = 0.275 + reg.coef_*x_matrix
fig = plt.plot(x, yhat, lw=4, c="blue", label="regression label")
plt.xlabel("SAT", fontsize=20)
plt.ylabel("GPA", fontsize=20)
plt.show()

# Calculating the R-squared

In [32]:
reg.score(x,y)

0.4066811952814282

### Formula for Adjusted R-square R^2

$R^2_{adj.} = 1 - (1 - R^2)*\frac{n-1}{n-p-1}$

In [33]:
adj_R_squared = 1 - (1 - (reg.score(x,y)))*((len(data)-1)/(len(data)-2-1))
adj_R_squared

0.39203134825134

In [34]:
x.shape

(84, 2)

# Feature selection

In [35]:
from sklearn.feature_selection import f_regression

In [36]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [37]:
p_values = f_regression(x,y)[1]

In [38]:
p_values.round(3)

array([0.   , 0.676])

# Creating a summary table

In [39]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=["Features"])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [40]:
reg_summary["Coefficient"] = reg.coef_
reg_summary["P-values"] = p_values.round(3)
reg_summary

Features  Coefficient  P-values
0         SAT     0.001654     0.000
1  Rand 1,2,3    -0.008270     0.676

# Standardization

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
scaler = StandardScaler()

In [43]:
scaler.fit(x)

StandardScaler()

In [44]:
x_scaled = scaler.transform(x)

In [45]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with scaled features

In [46]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [47]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [48]:
reg.intercept_

3.330238095238095

In [49]:
reg_summary = pd.DataFrame([["Bias"], ["SAT"], ["Rand 1,2,3"]], columns=["Features"])
reg_summary["Weights"] = reg.intercept_, reg.coef_[0], reg.coef_[1]
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

# Making predictions with the standardized coeeficients (weights)

In [50]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns=["SAT", "Rand 1,2,3"])
new_data.head()

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [51]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [52]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [53]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

# What if we removed the "Rand 1,2,3" feature?

In [54]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [55]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])